//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_Omega
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID_Applic { get; set; }
        public int NumApplic { get; set; }
        public System.DateTime DateApplic { get; set; }
        public int ID_Department { get; set; }
        public int ID_Status { get; set; }
        public int ID_Type { get; set; }
        public int ID_Staff { get; set; }
        public int ID_Corpus { get; set; }
        public string Entrance { get; set; }
        public string Room { get; set; }
        public string Theme { get; set; }
        public string Remark { get; set; }
    
        public virtual Corpus Corpus { get; set; }
        public virtual Department Department { get; set; }
        public virtual StatusAp StatusAp { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TypeAp TypeAp { get; set; }
    }
}
